=== alicemaria696/Lab4xml/resturant.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="www.abc.com/resturant" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="resturant">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" name="placename">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="place" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="cafename">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element minOccurs="0" maxOccurs="unbounded" name="cafe" type="xs:string"></xs:element>
								<xs:element minOccurs="0" maxOccurs="unbounded" name="time" type="xs:string"></xs:element>
							</xs:choice>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="menu">
					<xs:complexType>
						<xs:sequence>
							<xs:simpleType name="foodtype" type="xs:string">
							    <xs:restriction base="xs:string">
							        <xs:enumeration value="Italian"/>
									<xs:enumeration value="Chinese"/>
									<xs:enumeration value="American"/>
									<xs:enumeration value="Deserts"/>
									<xs:enumeration value="Beverages"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="food">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="fooditem">
								<xs:complexType>
									<xs:sequence>
										<xs:element minOccurs="0" name="name" type="xs:string"></xs:element>
										<xs:element minOccurs="0" name="cost" type="xs:string"></xs:element>
									</xs:sequence>
									<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="Ambience">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="type" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element minOccurs="0" name="travel">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="traveltype">
								<xs:complexType>
									<xs:sequence>
										<xs:choice maxOccurs="unbounded">
											<xs:element minOccurs="0" maxOccurs="unbounded" name="name" type="xs:string"></xs:element>
											<xs:element minOccurs="0" maxOccurs="unbounded" name="price" type="xs:string"></xs:element>
											<xs:element minOccurs="0" maxOccurs="unbounded" name="own" type="xs:string"></xs:element>
										</xs:choice>
									</xs:sequence>
									<xs:attribute name="type" type="xs:string" use="optional"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
                <xs:element>
                   <xs:simpleType name="modeType">
                     <xs:restriction base="xs:string">
                       <xs:enumeration value="Gpay"/>
                       <xs:enumeration value="PhonePe"/>
                       <xs:enumeration value="PayTM"/>
                     </xs:restriction>
                    </xs:simpleType>
                </xs:element>
				<xs:element minOccurs="0" name="discount">
					<xs:complexType>
						<xs:sequence>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="voucher" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== alicemaria696/Lab4xml/resturant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resturant SYSTEM "resturant.dtd">
<?xml-stylesheet href="resturantdone.xsl"?>
<resturant xmlns="www.abc.com/resturant" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.abc.com/resturant resturant.xsd">
   <placename>
      <place>HSR</place>
      <place>Koramangala</place>
      <place>Madivala</place>
      <place>ChurchStreet</place>
   </placename>
   <cafename>
      <cafe>Rameshwaram</cafe>
      <time>6AM - 11PM</time>
      <cafe>Akkacafe</cafe>
      <time>9AM - 10PM</time>
      <cafe>Truffles</cafe>
      <time>11AM - 12PM</time>
      <cafe>Alchemy</cafe>
      <time>10AM - 11PM</time>
   </cafename>
   <menu>
      <foodtype>Veg</foodtype>
      <foodtype>Non-veg</foodtype>
      <foodtype>Ketodiet</foodtype>
   </menu>
   <food>
      <fooditem type="Italian">
         <name>Pasta</name>
         <cost>350/-</cost>
      </fooditem>
      <fooditem type="Chinese">
         <name>Noodles</name>
         <cost>200/-</cost>
      </fooditem>
      <fooditem type="Italian">
         <name>Pizza</name>
         <cost>300/-</cost>
      </fooditem>
      <fooditem type="American">
         <name>Burger</name>
         <cost>190/-</cost>
      </fooditem>
      <fooditem type="Desserts">
         <name>Tiramisu</name>
         <cost>290/-</cost>
      </fooditem>
      <fooditem type="Beverages">
         <name>Milkshakes</name>
         <cost>190/-</cost>
      </fooditem>
   </food>
   <Ambience>
      <type>Pottery</type>
      <type>Artitery</type>
      <type>Pub</type>
      <type>Club</type>
   </Ambience>
   <travel>
      <traveltype type="bus">
         <name>Koramangala</name>
         <price>20/-</price>
         <name>HSR</name>
         <price>30/-</price>
      </traveltype>
      <traveltype type="car">
         <own>Disel</own>
         <own>Petrol</own>
      </traveltype>
      <traveltype type="vechile">
         <own>Disel</own>
         <own>Petrol</own>
      </traveltype>
      <traveltype type="metro">
         <name>Koramangala</name>
         <price>20/-</price>
         <name>HSR</name>
         <price>30/-</price>
      </traveltype>
   </travel>
   <payment>
      <mode>Gpay</mode>
      <mode>PhonePe</mode>
      <mode>PayTM</mode>
   </payment>
   <discount>
      <voucher>Swiggy</voucher>
      <voucher>Zomato Gold</voucher>
      <voucher>Permium</voucher>
   </discount>
   </resturant>
